### ISSUE TITLE
Invalid Extended Type at offset 0 val 7

### ISSUE THREAD

**Issue by sunknudsen** [runk/node-maxmind#62]
Hey guys,

Using watchForUpdates : true

When I run the following:

```
wget http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz
gunzip -f GeoLite2-City.mmdb.gz
```

My app crashes with errors:

"error": {
    "message": "ENOENT: no such file or directory, open './GeoLite2-City.mmdb'",
    "stack": "Error: ENOENT: no such file or directory, open './GeoLite2-City.mmdb'\n    at Error (native)\n"
}

"error": {
    "message": "Invalid Extended Type at offset 0 val 7",
    "stack": "Error: Invalid Extended Type at offset 0 val 7\n    at Decoder.decode (***/node_modules/maxmind/lib/decoder.js:54:13)\n    at new Metadata (***/node_modules/maxmind/lib/metadata.js:15:26)\n    at Reader.load (***/node_modules/maxmind/lib/reader.js:27:19)\n    at new Reader (***/node_modules/maxmind/lib/reader.js:21:8)\n    at ***/node_modules/maxmind/index.js:18:18\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)\n"
}

Once the app is reloaded, all is good.

Is this a timing issue?

Best,

Sun

**Comment by runk** [comment]
Feels that your'e trying to use .gz file. I think I might add a check for this.

**Comment by sunknudsen** [comment]
Hi Dmitry,

I updated my script to extract and them override GeoLite2-City.mmdb.

```
wget -O ./GeoLite2-City.mmdb.gz http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz
gunzip -c ./GeoLite2-City.mmdb.gz > ./GeoLite2-City.mmdb.tmp
mv ./GeoLite2-City.mmdb.tmp ./GeoLite2-City.mmdb
```

My bet is that the node file watch was trying to open the file as it was being extracted. Makes sense?

Will report back tomorrow to close the issue if the fix worked in production.

Thanks for the great library by the way!

Sun

**Comment by runk** [comment]
I've added a check for gzip format in v2.2.0 - you can check it out.

**Comment by sunknudsen** [comment]
Hey @runk,

The problem appears to be that `{ watchForUpdates: true }` was trying to load the `.mmdb` file as it was being extracted.

Using a tmp file and then calling mv fixed the timing issue.

```
wget -O ./GeoLite2-City.mmdb.gz http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz
gunzip -c ./GeoLite2-City.mmdb.gz > ./GeoLite2-City.mmdb.tmp
mv ./GeoLite2-City.mmdb.tmp ./GeoLite2-City.mmdb
```

Have a great day,

Sun

**Comment by runk** [comment]
A-ha! Good old race condition.

**Comment by natanavra** [comment]
Sorry to revive an old thread
But this still happens with geolite2-redist, maybe it's related
geolite2-dist: 1.0.4
maxmind: 4.1.0
